# -*- coding: utf-8 -*-
"""Python_refresher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtMF4b81PB4vO4hkPIZhPAYPvxvrIzI8

Variables
"""

# Create a labeled storage basket and put a number inside
Tomato_price = 150
Pepper_price = 80

# Pull the value out of the baskets
print(Tomato_price)
print(Pepper_price)

"""Variables (ML Anchor)"""

# --- THE CLUES (Features grouped as X) ---
rainfall_mm = 45.2  #Clue 1
bags_available = 100  #Clue 2

# ---- THE GOAL (Target labeled as y) ---
predicted_price = 3200 # What our AI calculates

print("Input (x):", rainfall_mm, "mm rain,", bags_available, "bags.")
print("output (y):",predicted_price,"LRD.")

"""Understanding Print Statement"""

Liberia = 1847
print (Liberia)
print ("liberia")

"""understanding Variable"""

plum= 50
print("Plum previous price was :",plum)
plum =80
print("plum new price is:",plum)