# -*- coding: utf-8 -*-
"""Tour.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fqBxGnAM7DUbcc7fhmYqhQf8HKU04Av
"""

A=2
B=3
C=2+3
print(C)

"""Example of String

"""

Greetings= "Advice na, pror"
print (Greetings)